import figma from "@figma/code-connect";
import { DialogModal } from "primitives";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DialogModal,
  "https://www.figma.com/design/Pf48iHeVhfGEUYCgLamKd5?node-id=192-31534",
  {
    props: { children: figma.children("Dialog Body") },
    example: (props) => (
      <DialogModal isDismissable isOpen={true} onOpenChange={() => {}}>
        {props.children}
      </DialogModal>
    ),
  },
);
